import { IQuestion, IDestination, IMysteryClue, IPlayer } from './types.js';

// ==========================================
// 1. HIRAGANA QUESTIONS (52 total across 3 levels)
// ==========================================
export const HIRAGANA_QUESTIONS: Omit<IQuestion, 'id'>[] = [
  // --- LEVEL 1: Basic vowels and K / S / T lines (Beginner) ---
  { gameType: 'hiragana', question: 'あ', subtext: 'What romaji sound does this hiragana make?', options: ['a', 'o', 'u', 'e'], correctAnswer: 'a', difficulty: 'beginner', points: 100, explanation: '「あ」 is the vowel "a" as in father.' },
  { gameType: 'hiragana', question: 'い', subtext: 'What romaji sound does this hiragana make?', options: ['i', 'e', 'u', 'a'], correctAnswer: 'i', difficulty: 'beginner', points: 100, explanation: '「い」 is "i", pronounced like "ee".' },
  { gameType: 'hiragana', question: 'う', subtext: 'What romaji sound does this hiragana make?', options: ['u', 'o', 'a', 'n'], correctAnswer: 'u', difficulty: 'beginner', points: 100, explanation: '「う」 is "u", pronounced like "oo".' },
  { gameType: 'hiragana', question: 'え', subtext: 'What romaji sound does this hiragana make?', options: ['e', 'i', 'a', 'o'], correctAnswer: 'e', difficulty: 'beginner', points: 100, explanation: '「え」 is "e", pronounced like "eh".' },
  { gameType: 'hiragana', question: 'お', subtext: 'What romaji sound does this hiragana make?', options: ['o', 'a', 'u', 'ko'], correctAnswer: 'o', difficulty: 'beginner', points: 100, explanation: '「お」 is "o", pronounced like "oh".' },
  { gameType: 'hiragana', question: 'か', subtext: 'What romaji sound does this hiragana make?', options: ['ka', 'ki', 'ku', 'sa'], correctAnswer: 'ka', difficulty: 'beginner', points: 100, explanation: '「か」 is "ka".' },
  { gameType: 'hiragana', question: 'き', subtext: 'What romaji sound does this hiragana make?', options: ['ki', 'sa', 'chi', 'ko'], correctAnswer: 'ki', difficulty: 'beginner', points: 100, explanation: '「き」 looks like a key, representing "ki".' },
  { gameType: 'hiragana', question: 'く', subtext: 'What romaji sound does this hiragana make?', options: ['ku', 'he', 'te', 'tsu'], correctAnswer: 'ku', difficulty: 'beginner', points: 100, explanation: '「く」 looks like a cuckoo beak, representing "ku".' },
  { gameType: 'hiragana', question: 'け', subtext: 'What romaji sound does this hiragana make?', options: ['ke', 'ha', 'ho', 'ni'], correctAnswer: 'ke', difficulty: 'beginner', points: 100, explanation: '「け」 is "ke".' },
  { gameType: 'hiragana', question: 'こ', subtext: 'What romaji sound does this hiragana make?', options: ['ko', 'ni', 'to', 'i'], correctAnswer: 'ko', difficulty: 'beginner', points: 100, explanation: '「こ」 is two horizontal curved strokes for "ko".' },
  { gameType: 'hiragana', question: 'さ', subtext: 'What romaji sound does this hiragana make?', options: ['sa', 'chi', 'ki', 'ta'], correctAnswer: 'sa', difficulty: 'beginner', points: 100, explanation: '「さ」 is "sa".' },
  { gameType: 'hiragana', question: 'し', subtext: 'What romaji sound does this hiragana make?', options: ['shi', 'tsu', 'ku', 'i'], correctAnswer: 'shi', difficulty: 'beginner', points: 100, explanation: '「し」 is a fishing hook shape representing "shi".' },
  { gameType: 'hiragana', question: 'す', subtext: 'What romaji sound does this hiragana make?', options: ['su', 'nu', 'mu', 'fu'], correctAnswer: 'su', difficulty: 'beginner', points: 100, explanation: '「す」 has a loop like spiral noodles for "su".' },
  { gameType: 'hiragana', question: 'せ', subtext: 'What romaji sound does this hiragana make?', options: ['se', 'ke', 'ya', 'mo'], correctAnswer: 'se', difficulty: 'beginner', points: 100, explanation: '「せ」 is "se".' },
  { gameType: 'hiragana', question: 'そ', subtext: 'What romaji sound does this hiragana make?', options: ['so', 'te', 'ro', 'ru'], correctAnswer: 'so', difficulty: 'beginner', points: 100, explanation: '「そ」 is a zigzag stroke for "so".' },
  { gameType: 'hiragana', question: 'た', subtext: 'What romaji sound does this hiragana make?', options: ['ta', 'na', 'da', 'ka'], correctAnswer: 'ta', difficulty: 'beginner', points: 100, explanation: '「た」 looks like "ta" written in cursive.' },
  { gameType: 'hiragana', question: 'ち', subtext: 'What romaji sound does this hiragana make?', options: ['chi', 'sa', 'ta', 'ra'], correctAnswer: 'chi', difficulty: 'beginner', points: 100, explanation: '「ち」 is "chi", resembling the number 5.' },
  { gameType: 'hiragana', question: 'つ', subtext: 'What romaji sound does this hiragana make?', options: ['tsu', 'shi', 'u', 'ku'], correctAnswer: 'tsu', difficulty: 'beginner', points: 100, explanation: '「つ」 is a single wave curve for "tsu".' },

  // --- LEVEL 2: N, H, M, Y, R, W lines (Intermediate) ---
  { gameType: 'hiragana', question: 'な', subtext: 'Identify the romaji reading', options: ['na', 'ta', 'me', 'ne'], correctAnswer: 'na', difficulty: 'intermediate', points: 120, explanation: '「な」 is "na".' },
  { gameType: 'hiragana', question: 'に', subtext: 'Identify the romaji reading', options: ['ni', 'ko', 'ta', 'i'], correctAnswer: 'ni', difficulty: 'intermediate', points: 120, explanation: '「に」 is "ni", representing two needles.' },
  { gameType: 'hiragana', question: 'ぬ', subtext: 'Identify the romaji reading', options: ['nu', 'ne', 'me', 'wa'], correctAnswer: 'nu', difficulty: 'intermediate', points: 120, explanation: '「ぬ」 is "nu", with a looped tail.' },
  { gameType: 'hiragana', question: 'ね', subtext: 'Identify the romaji reading', options: ['ne', 're', 'wa', 'nu'], correctAnswer: 'ne', difficulty: 'intermediate', points: 120, explanation: '「ね」 is "ne", with a curled spiral.' },
  { gameType: 'hiragana', question: 'の', subtext: 'Identify the romaji reading', options: ['no', 'me', 'e', 'a'], correctAnswer: 'no', difficulty: 'intermediate', points: 120, explanation: '「の」 is a simple circular spiral for "no".' },
  { gameType: 'hiragana', question: 'は', subtext: 'Identify the romaji reading', options: ['ha', 'ho', 'ke', 'ma'], correctAnswer: 'ha', difficulty: 'intermediate', points: 120, explanation: '「は」 is "ha".' },
  { gameType: 'hiragana', question: 'ひ', subtext: 'Identify the romaji reading', options: ['hi', 'te', 'shi', 'to'], correctAnswer: 'hi', difficulty: 'intermediate', points: 120, explanation: '「ひ」 is "hi", shaped like a smiling face.' },
  { gameType: 'hiragana', question: 'ふ', subtext: 'Identify the romaji reading', options: ['fu', 'u', 'o', 'su'], correctAnswer: 'fu', difficulty: 'intermediate', points: 120, explanation: '「ふ」 is "fu" (or hu), depicting Mount Fuji peak.' },
  { gameType: 'hiragana', question: 'へ', subtext: 'Identify the romaji reading', options: ['he', 'ku', 'tsu', 'te'], correctAnswer: 'he', difficulty: 'intermediate', points: 120, explanation: '「へ」 is "he", shaped like an upward arrow.' },
  { gameType: 'hiragana', question: 'ほ', subtext: 'Identify the romaji reading', options: ['ho', 'ha', 'ma', 'ke'], correctAnswer: 'ho', difficulty: 'intermediate', points: 120, explanation: '「ほ」 is "ho", featuring a top roof cap.' },
  { gameType: 'hiragana', question: 'ま', subtext: 'Identify the romaji reading', options: ['ma', 'ho', 'ha', 'mo'], correctAnswer: 'ma', difficulty: 'intermediate', points: 120, explanation: '「ま」 is "ma".' },
  { gameType: 'hiragana', question: 'み', subtext: 'Identify the romaji reading', options: ['mi', 'me', 'sa', 'chi'], correctAnswer: 'mi', difficulty: 'intermediate', points: 120, explanation: '「み」 looks like the numeral 21 for "mi".' },
  { gameType: 'hiragana', question: 'む', subtext: 'Identify the romaji reading', options: ['mu', 'su', 'nu', 'fu'], correctAnswer: 'mu', difficulty: 'intermediate', points: 120, explanation: '「む」 sounds like a cow\'s moo.' },
  { gameType: 'hiragana', question: 'め', subtext: 'Identify the romaji reading', options: ['me', 'nu', 'ne', 'a'], correctAnswer: 'me', difficulty: 'intermediate', points: 120, explanation: '「め」 means eye in Japanese (me).' },
  { gameType: 'hiragana', question: 'も', subtext: 'Identify the romaji reading', options: ['mo', 'se', 'shi', 'ma'], correctAnswer: 'mo', difficulty: 'intermediate', points: 120, explanation: '「も」 looks like a fishing hook catching more worms.' },
  { gameType: 'hiragana', question: 'や', subtext: 'Identify the romaji reading', options: ['ya', 'yu', 'yo', 'se'], correctAnswer: 'ya', difficulty: 'intermediate', points: 120, explanation: '「や」 is "ya".' },
  { gameType: 'hiragana', question: 'ゆ', subtext: 'Identify the romaji reading', options: ['yu', 'ya', 'yo', 'a'], correctAnswer: 'yu', difficulty: 'intermediate', points: 120, explanation: '「ゆ」 looks like a fish in a hot spring (yu).' },
  { gameType: 'hiragana', question: 'よ', subtext: 'Identify the romaji reading', options: ['yo', 'ma', 'ko', 'to'], correctAnswer: 'yo', difficulty: 'intermediate', points: 120, explanation: '「よ」 is "yo".' },
  { gameType: 'hiragana', question: 'ら', subtext: 'Identify the romaji reading', options: ['ra', 'chi', 'ro', 'ru'], correctAnswer: 'ra', difficulty: 'intermediate', points: 120, explanation: '「ら」 is "ra".' },
  { gameType: 'hiragana', question: 'り', subtext: 'Identify the romaji reading', options: ['ri', 'i', 're', 'ka'], correctAnswer: 'ri', difficulty: 'intermediate', points: 120, explanation: '「り」 is two vertical reeds for "ri".' },
  { gameType: 'hiragana', question: 'る', subtext: 'Identify the romaji reading', options: ['ru', 'ro', '3', 'so'], correctAnswer: 'ru', difficulty: 'intermediate', points: 120, explanation: '「る」 has a loop at the end (unlike ろ).' },
  { gameType: 'hiragana', question: 'れ', subtext: 'Identify the romaji reading', options: ['re', 'wa', 'ne', 'ke'], correctAnswer: 're', difficulty: 'intermediate', points: 120, explanation: '「れ」 flares outward at the bottom.' },
  { gameType: 'hiragana', question: 'ろ', subtext: 'Identify the romaji reading', options: ['ro', 'ru', 'so', 'to'], correctAnswer: 'ro', difficulty: 'intermediate', points: 120, explanation: '「ろ」 is open at the bottom without a loop.' },
  { gameType: 'hiragana', question: 'わ', subtext: 'Identify the romaji reading', options: ['wa', 're', 'ne', 'o'], correctAnswer: 'wa', difficulty: 'intermediate', points: 120, explanation: '「わ」 has a smooth curved belly for "wa".' },
  { gameType: 'hiragana', question: 'を', subtext: 'Identify the romaji reading', options: ['wo / o', 'wa', 'ro', 'to'], correctAnswer: 'wo / o', difficulty: 'intermediate', points: 120, explanation: '「を」 is the object particle "wo" (pronounced o).' },
  { gameType: 'hiragana', question: 'ん', subtext: 'Identify the romaji reading', options: ['n', 'so', 'ri', 'shi'], correctAnswer: 'n', difficulty: 'intermediate', points: 120, explanation: '「ん」 is the only standalone nasal consonant "n".' },

  // --- LEVEL 3: Dakuten, Handakuten, and Yoon Combinations (Advanced) ---
  { gameType: 'hiragana', question: 'が', subtext: 'Notice the dakuten (tenten) marks', options: ['ga', 'ka', 'za', 'da'], correctAnswer: 'ga', difficulty: 'advanced', points: 150, explanation: 'か + dakuten becomes voiced "ga".' },
  { gameType: 'hiragana', question: 'ざ', subtext: 'Notice the dakuten (tenten) marks', options: ['za', 'sa', 'da', 'ba'], correctAnswer: 'za', difficulty: 'advanced', points: 150, explanation: 'さ + dakuten becomes "za".' },
  { gameType: 'hiragana', question: 'だ', subtext: 'Notice the dakuten (tenten) marks', options: ['da', 'ta', 'ba', 'za'], correctAnswer: 'da', difficulty: 'advanced', points: 150, explanation: 'た + dakuten becomes "da".' },
  { gameType: 'hiragana', question: 'ば', subtext: 'Notice the dakuten marks', options: ['ba', 'pa', 'ha', 'ma'], correctAnswer: 'ba', difficulty: 'advanced', points: 150, explanation: 'は + dakuten becomes "ba".' },
  { gameType: 'hiragana', question: 'ぱ', subtext: 'Notice the handakuten (maru circle) mark', options: ['pa', 'ba', 'ha', 'fa'], correctAnswer: 'pa', difficulty: 'advanced', points: 150, explanation: 'は + maru (handakuten) becomes "pa".' },
  { gameType: 'hiragana', question: 'きゃ', subtext: 'Identify this combination sound (Yoon)', options: ['kya', 'kiya', 'ka', 'kyo'], correctAnswer: 'kya', difficulty: 'advanced', points: 150, explanation: 'き + small ゃ contracts to "kya".' },
  { gameType: 'hiragana', question: 'しゃ', subtext: 'Identify this combination sound (Yoon)', options: ['sha', 'shiya', 'sa', 'chu'], correctAnswer: 'sha', difficulty: 'advanced', points: 150, explanation: 'し + small ゃ makes "sha".' },
  { gameType: 'hiragana', question: 'きょ', subtext: 'Identify this combination sound (Yoon)', options: ['kyo', 'kiyo', 'ko', 'ryo'], correctAnswer: 'kyo', difficulty: 'advanced', points: 150, explanation: 'き + small ょ makes "kyo" as in Kyoto.' },
  { gameType: 'hiragana', question: 'とうきょう', subtext: 'Read this famous city name written in hiragana', options: ['Tokyo', 'Kyoto', 'Osaka', 'Nagoya'], correctAnswer: 'Tokyo', difficulty: 'advanced', points: 150, explanation: 'とうきょう = Toukyou (Tokyo).' },
  { gameType: 'hiragana', question: 'ありがとう', subtext: 'Read this polite expression in hiragana', options: ['Arigatou (Thank you)', 'Konnichiwa (Hello)', 'Sayounara (Goodbye)', 'Gomen (Sorry)'], correctAnswer: 'Arigatou (Thank you)', difficulty: 'advanced', points: 150, explanation: 'ありがとう means "Thank you".' },
];

// ==========================================
// 2. VOCABULARY QUEST (54 questions across 6 categories)
// ==========================================
export const VOCABULARY_QUESTIONS: Omit<IQuestion, 'id'>[] = [
  // --- Category: Food (🍜) ---
  { gameType: 'vocabulary', category: 'Food', question: 'みず (Mizu)', subtext: 'Translate this Japanese word into English', options: ['Water', 'Food', 'Tea', 'Rice'], correctAnswer: 'Water', difficulty: 'beginner', points: 100, explanation: 'みず (Mizu) = Fresh cold water.' },
  { gameType: 'vocabulary', category: 'Food', question: 'ごはん (Gohan)', subtext: 'Translate this Japanese word into English', options: ['Cooked Rice / Meal', 'Noodles', 'Fish', 'Bread'], correctAnswer: 'Cooked Rice / Meal', difficulty: 'beginner', points: 100, explanation: 'ごはん (Gohan) refers to rice or meals.' },
  { gameType: 'vocabulary', category: 'Food', question: 'おちゃ (Ocha)', subtext: 'Translate this Japanese word into English', options: ['Green Tea', 'Coffee', 'Juice', 'Milk'], correctAnswer: 'Green Tea', difficulty: 'beginner', points: 100, explanation: 'おちゃ (Ocha) is traditional Japanese green tea.' },
  { gameType: 'vocabulary', category: 'Food', question: 'おいしい (Oishii)', subtext: 'What does this common food phrase mean?', options: ['Delicious', 'Hot', 'Sweet', 'Spicy'], correctAnswer: 'Delicious', difficulty: 'beginner', points: 100, explanation: 'おいしい (Oishii) means delicious or tasty!' },
  { gameType: 'vocabulary', category: 'Food', question: 'How do you say "Ramen" in Japanese?', subtext: 'English → Japanese', options: ['らーめん', 'すし', 'そば', 'うどん'], correctAnswer: 'らーめん', difficulty: 'beginner', points: 100, explanation: 'Ramen is written らーめん in hiragana or ラーメン in katakana.' },
  { gameType: 'vocabulary', category: 'Food', question: 'How do you say "Fish" in Japanese?', subtext: 'English → Japanese', options: ['さかな (Sakana)', 'にく (Niku)', 'たまご (Tamago)', 'やさい (Yasai)'], correctAnswer: 'さかな (Sakana)', difficulty: 'intermediate', points: 120, explanation: '魚 / さかな (Sakana) means fish.' },
  { gameType: 'vocabulary', category: 'Food', question: 'How do you say "Meat" in Japanese?', subtext: 'English → Japanese', options: ['にく (Niku)', 'さかな (Sakana)', 'パン (Pan)', 'くだもの (Kudamono)'], correctAnswer: 'にく (Niku)', difficulty: 'intermediate', points: 120, explanation: '肉 / にく (Niku) means meat.' },
  { gameType: 'vocabulary', category: 'Food', question: 'いただきます (Itadakimasu)', subtext: 'When do people say this essential phrase?', options: ['Before eating a meal', 'After eating a meal', 'When saying goodbye', 'When waking up'], correctAnswer: 'Before eating a meal', difficulty: 'intermediate', points: 120, explanation: 'Itadakimasu expresses humble gratitude before enjoying a meal.' },
  { gameType: 'vocabulary', category: 'Food', question: 'ごちそうさまでした (Gochisousama deshita)', subtext: 'When is this respectful phrase spoken?', options: ['After finishing a meal', 'When entering a restaurant', 'When paying a bill', 'Before taking the first bite'], correctAnswer: 'After finishing a meal', difficulty: 'advanced', points: 150, explanation: 'Spoken after eating to thank the host and chef for the feast.' },

  // --- Category: Education (🏫) ---
  { gameType: 'vocabulary', category: 'Education', question: 'がっこう (Gakkou)', subtext: 'Translate this word to English', options: ['School', 'Library', 'Hospital', 'Station'], correctAnswer: 'School', difficulty: 'beginner', points: 100, explanation: '学校 / がっこう (Gakkou) means school.' },
  { gameType: 'vocabulary', category: 'Education', question: 'せんせい (Sensei)', subtext: 'What does this honorable title mean?', options: ['Teacher / Master', 'Student', 'Principal', 'Doctor only'], correctAnswer: 'Teacher / Master', difficulty: 'beginner', points: 100, explanation: '先生 / せんせい (Sensei) refers to a teacher or instructor.' },
  { gameType: 'vocabulary', category: 'Education', question: 'がくせい (Gakusei)', subtext: 'Translate this word to English', options: ['Student', 'Teacher', 'Worker', 'Author'], correctAnswer: 'Student', difficulty: 'beginner', points: 100, explanation: '学生 / がくせい (Gakusei) means student.' },
  { gameType: 'vocabulary', category: 'Education', question: 'ほん (Hon)', subtext: 'Translate this Japanese word into English', options: ['Book', 'Pen', 'Bag', 'Desk'], correctAnswer: 'Book', difficulty: 'beginner', points: 100, explanation: '本 / ほん (Hon) means book.' },
  { gameType: 'vocabulary', category: 'Education', question: 'How do you say "Classroom" in Japanese?', subtext: 'English → Japanese', options: ['きょうしつ (Kyoushitsu)', 'しょくどう (Shokudou)', 'としょかん (Toshokan)', 'へや (Heya)'], correctAnswer: 'きょうしつ (Kyoushitsu)', difficulty: 'intermediate', points: 120, explanation: '教室 / きょうしつ (Kyoushitsu) is a classroom.' },
  { gameType: 'vocabulary', category: 'Education', question: 'How do you say "Library" in Japanese?', subtext: 'English → Japanese', options: ['としょかん (Toshokan)', 'えき (Eki)', 'びょういん (Byouin)', 'ぎんこう (Ginkou)'], correctAnswer: 'としょかん (Toshokan)', difficulty: 'intermediate', points: 120, explanation: '図書館 / としょかん (Toshokan) means library.' },
  { gameType: 'vocabulary', category: 'Education', question: 'しゅくだい (Shukudai)', subtext: 'Translate this academic term to English', options: ['Homework', 'Exam', 'Graduation', 'Recess'], correctAnswer: 'Homework', difficulty: 'intermediate', points: 120, explanation: '宿題 / しゅくだい (Shukudai) means homework.' },
  { gameType: 'vocabulary', category: 'Education', question: 'べんきょう (Benkyou)', subtext: 'What does this verb/noun mean?', options: ['Studying', 'Exercising', 'Sleeping', 'Cooking'], correctAnswer: 'Studying', difficulty: 'advanced', points: 150, explanation: '勉強 / べんきょう (Benkyou) means study.' },
  { gameType: 'vocabulary', category: 'Education', question: 'しけん (Shiken)', subtext: 'Translate to English', options: ['Exam / Test', 'Presentation', 'Syllabus', 'Textbook'], correctAnswer: 'Exam / Test', difficulty: 'advanced', points: 150, explanation: '試験 / しけん (Shiken) means examination or test.' },

  // --- Category: Travel (🚄) ---
  { gameType: 'vocabulary', category: 'Travel', question: 'でんしゃ (Densha)', subtext: 'Translate this transportation word', options: ['Train (Electric)', 'Airplane', 'Bicycle', 'Car'], correctAnswer: 'Train (Electric)', difficulty: 'beginner', points: 100, explanation: '電車 / でんしゃ (Densha) is an electric passenger train.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'えき (Eki)', subtext: 'Translate this essential travel location', options: ['Station', 'Airport', 'Hotel', 'Market'], correctAnswer: 'Station', difficulty: 'beginner', points: 100, explanation: '駅 / えき (Eki) means train or metro station.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'しんかんせん (Shinkansen)', subtext: 'What is this world-famous Japanese train?', options: ['Bullet Train (High-speed rail)', 'Subway', 'Steam locomotive', 'Cable car'], correctAnswer: 'Bullet Train (High-speed rail)', difficulty: 'beginner', points: 100, explanation: 'The Shinkansen is Japan\'s iconic high-speed bullet train.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'How do you say "Airport" in Japanese?', subtext: 'English → Japanese', options: ['くうこう (Kuukou)', 'えき (Eki)', 'みなと (Minato)', 'みち (Michi)'], correctAnswer: 'くうこう (Kuukou)', difficulty: 'intermediate', points: 120, explanation: '空港 / くうこう (Kuukou) means airport.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'How do you say "Ticket" in Japanese?', subtext: 'English → Japanese', options: ['きっぷ (Kippu)', 'ちず (Chizu)', 'おかね (Okane)', 'パスポート (Pasupo-to)'], correctAnswer: 'きっぷ (Kippu)', difficulty: 'intermediate', points: 120, explanation: '切符 / きっぷ (Kippu) means ticket.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'ちず (Chizu)', subtext: 'What item helps you find your way?', options: ['Map', 'Compass', 'Clock', 'Ticket'], correctAnswer: 'Map', difficulty: 'intermediate', points: 120, explanation: '地図 / ちず (Chizu) means map.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'りょこう (Ryokou)', subtext: 'Translate this activity', options: ['Travel / Trip', 'Shopping', 'Business', 'Hiking'], correctAnswer: 'Travel / Trip', difficulty: 'intermediate', points: 120, explanation: '旅行 / りょこう (Ryokou) means trip or travel.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'ひこうき (Hikouki)', subtext: 'Translate this vehicle', options: ['Airplane', 'Helicopter', 'Ferry', 'Bus'], correctAnswer: 'Airplane', difficulty: 'advanced', points: 150, explanation: '飛行機 / ひこうき (Hikouki) means airplane.' },
  { gameType: 'vocabulary', category: 'Travel', question: 'きっぷうりば (Kippu uriba)', subtext: 'What sign would you look for at the station?', options: ['Ticket counter / Ticket machine area', 'Lost and found', 'Platform exit', 'Restroom'], correctAnswer: 'Ticket counter / Ticket machine area', difficulty: 'advanced', points: 150, explanation: '切符売り場 (Kippu uriba) is where tickets are purchased.' },

  // --- Category: People (👨👩👧) ---
  { gameType: 'vocabulary', category: 'People', question: 'ともだち (Tomodachi)', subtext: 'Translate to English', options: ['Friend', 'Family', 'Teacher', 'Neighbor'], correctAnswer: 'Friend', difficulty: 'beginner', points: 100, explanation: '友達 / ともだち (Tomodachi) means friend.' },
  { gameType: 'vocabulary', category: 'People', question: 'ひと (Hito)', subtext: 'Translate to English', options: ['Person / People', 'Child', 'Adult', 'Baby'], correctAnswer: 'Person / People', difficulty: 'beginner', points: 100, explanation: '人 / ひと (Hito) means person.' },
  { gameType: 'vocabulary', category: 'People', question: 'かぞく (Kazoku)', subtext: 'Translate to English', options: ['Family', 'Parents', 'Brothers', 'Relatives'], correctAnswer: 'Family', difficulty: 'beginner', points: 100, explanation: '家族 / かぞく (Kazoku) means family.' },
  { gameType: 'vocabulary', category: 'People', question: 'How do you say "Mother" in Japanese when speaking of your own?', subtext: 'English → Japanese', options: ['はは (Haha)', 'ちち (Chichi)', 'あね (Ane)', 'いもうと (Imouto)'], correctAnswer: 'はは (Haha)', difficulty: 'intermediate', points: 120, explanation: '母 / はは (Haha) is one\'s own mother; お母さん (Okaasan) is respectful.' },
  { gameType: 'vocabulary', category: 'People', question: 'How do you say "Father" in Japanese when speaking of your own?', subtext: 'English → Japanese', options: ['ちち (Chichi)', 'はは (Haha)', 'あに (Ani)', 'おとうと (Otouto)'], correctAnswer: 'ちち (Chichi)', difficulty: 'intermediate', points: 120, explanation: '父 / ちち (Chichi) is one\'s own father; お父さん (Otousan) is polite.' },
  { gameType: 'vocabulary', category: 'People', question: 'こども (Kodomo)', subtext: 'Translate to English', options: ['Child / Children', 'Teenager', 'Elderly', 'Infant'], correctAnswer: 'Child / Children', difficulty: 'intermediate', points: 120, explanation: '子供 / こども (Kodomo) means child or children.' },
  { gameType: 'vocabulary', category: 'People', question: 'おとこのひと (Otoko no hito)', subtext: 'Translate to English', options: ['Man', 'Woman', 'Boy', 'Girl'], correctAnswer: 'Man', difficulty: 'intermediate', points: 120, explanation: '男の人 (Otoko no hito) means adult male or man.' },
  { gameType: 'vocabulary', category: 'People', question: 'おんなのひと (Onna no hito)', subtext: 'Translate to English', options: ['Woman', 'Man', 'Girl', 'Mother'], correctAnswer: 'Woman', difficulty: 'intermediate', points: 120, explanation: '女の人 (Onna no hito) means adult female or woman.' },
  { gameType: 'vocabulary', category: 'People', question: 'あかちゃん (Akachan)', subtext: 'Translate to English', options: ['Baby / Infant', 'Toddler', 'Youth', 'Puppy'], correctAnswer: 'Baby / Infant', difficulty: 'advanced', points: 150, explanation: '赤ちゃん / あかちゃん (Akachan) means baby or newborn.' },

  // --- Category: Daily Life (🏠) ---
  { gameType: 'vocabulary', category: 'Daily Life', question: 'いえ (Ie)', subtext: 'Translate to English', options: ['House / Home', 'Apartment', 'Room', 'Garden'], correctAnswer: 'House / Home', difficulty: 'beginner', points: 100, explanation: '家 / いえ (Ie) or うち (Uchi) means house or home.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'へや (Heya)', subtext: 'Translate to English', options: ['Room', 'Kitchen', 'Bathroom', 'Balcony'], correctAnswer: 'Room', difficulty: 'beginner', points: 100, explanation: '部屋 / へや (Heya) means room.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'How do you say "Hello / Good afternoon" in Japanese?', subtext: 'English → Japanese', options: ['こんにちは (Konnichiwa)', 'おはよう (Ohayou)', 'こんばんは (Konbanwa)', 'さようなら (Sayounara)'], correctAnswer: 'こんにちは (Konnichiwa)', difficulty: 'beginner', points: 100, explanation: 'こんにちは (Konnichiwa) is the standard daytime greeting.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'How do you say "Good morning" politely in Japanese?', subtext: 'English → Japanese', options: ['おはようございます (Ohayou gozaimasu)', 'こんにちは (Konnichiwa)', 'おやすみなさい (Oyasuminasai)', 'いただきます (Itadakimasu)'], correctAnswer: 'おはようございます (Ohayou gozaimasu)', difficulty: 'beginner', points: 100, explanation: 'おはようございます (Ohayou gozaimasu) is polite morning greeting.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'おかね (Okane)', subtext: 'Translate to English', options: ['Money', 'Wallet', 'Card', 'Price'], correctAnswer: 'Money', difficulty: 'intermediate', points: 120, explanation: 'お金 / おかね (Okane) means money.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'じかん (Jikan)', subtext: 'Translate to English', options: ['Time', 'Date', 'Hourglass', 'Calendar'], correctAnswer: 'Time', difficulty: 'intermediate', points: 120, explanation: '時間 / じかん (Jikan) means time or duration.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'とけい (Tokei)', subtext: 'Translate to English', options: ['Clock / Watch', 'Mirror', 'Phone', 'Door'], correctAnswer: 'Clock / Watch', difficulty: 'intermediate', points: 120, explanation: '時計 / とけい (Tokei) means clock or wristwatch.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'でんわ (Denwa)', subtext: 'Translate to English', options: ['Telephone / Phone call', 'Television', 'Electricity', 'Radio'], correctAnswer: 'Telephone / Phone call', difficulty: 'intermediate', points: 120, explanation: '電話 / でんわ (Denwa) means telephone.' },
  { gameType: 'vocabulary', category: 'Daily Life', question: 'おふろ (Ofuro)', subtext: 'What traditional relaxing fixture is this?', options: ['Japanese Bath', 'Bed', 'Kitchen sink', 'Shower booth only'], correctAnswer: 'Japanese Bath', difficulty: 'advanced', points: 150, explanation: 'お風呂 (Ofuro) is the traditional Japanese deep soaking tub.' },

  // --- Category: Nature (🌸) ---
  { gameType: 'vocabulary', category: 'Nature', question: 'さくら (Sakura)', subtext: 'Translate this national bloom to English', options: ['Cherry Blossom', 'Plum Blossom', 'Sunflower', 'Rose'], correctAnswer: 'Cherry Blossom', difficulty: 'beginner', points: 100, explanation: '桜 / さくら (Sakura) means cherry blossoms.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'やま (Yama)', subtext: 'Translate to English', options: ['Mountain', 'River', 'Forest', 'Ocean'], correctAnswer: 'Mountain', difficulty: 'beginner', points: 100, explanation: '山 / やま (Yama) means mountain.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'かわ (Kawa)', subtext: 'Translate to English', options: ['River', 'Lake', 'Ocean', 'Rain'], correctAnswer: 'River', difficulty: 'beginner', points: 100, explanation: '川 / かわ (Kawa) means river.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'How do you say "Sun" or "Day" in Japanese?', subtext: 'English → Japanese', options: ['ひ (Hi)', 'つき (Tsuki)', 'ほし (Hoshi)', 'そら (Sora)'], correctAnswer: 'ひ (Hi)', difficulty: 'intermediate', points: 120, explanation: '日 / ひ (Hi) means sun or day.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'How do you say "Moon" in Japanese?', subtext: 'English → Japanese', options: ['つき (Tsuki)', 'たいよう (Taiyou)', 'ほし (Hoshi)', 'あめ (Ame)'], correctAnswer: 'つき (Tsuki)', difficulty: 'intermediate', points: 120, explanation: '月 / つき (Tsuki) means moon.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'うみ (Umi)', subtext: 'Translate to English', options: ['Sea / Ocean', 'Beach', 'Wave', 'Island'], correctAnswer: 'Sea / Ocean', difficulty: 'intermediate', points: 120, explanation: '海 / うみ (Umi) means sea or ocean.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'あめ (Ame)', subtext: 'Translate this weather phenomenon', options: ['Rain', 'Snow', 'Wind', 'Cloud'], correctAnswer: 'Rain', difficulty: 'intermediate', points: 120, explanation: '雨 / あめ (Ame) means rain.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'ゆき (Yuki)', subtext: 'Translate this winter weather', options: ['Snow', 'Ice', 'Fog', 'Frost'], correctAnswer: 'Snow', difficulty: 'intermediate', points: 120, explanation: '雪 / ゆき (Yuki) means snow.' },
  { gameType: 'vocabulary', category: 'Nature', question: 'もみじ (Momiji)', subtext: 'What famous autumn nature spectacle is this?', options: ['Japanese Red Maple Leaves', 'Spring Grass', 'Bamboo Shoots', 'Winter Pine'], correctAnswer: 'Japanese Red Maple Leaves', difficulty: 'advanced', points: 150, explanation: '紅葉 / もみじ (Momiji) refers to Japanese maples turning crimson in autumn.' },
];

// ==========================================
// 3. KANJI MASTER (42 questions across Beginner, Intermediate, Advanced)
// ==========================================
export const KANJI_QUESTIONS: Omit<IQuestion, 'id'>[] = [
  // --- Beginner Kanji (N5 Level) ---
  { gameType: 'kanji', question: '日', subtext: 'What does this primary Kanji mean?', options: ['Sun / Day', 'Moon / Month', 'Fire', 'Water'], correctAnswer: 'Sun / Day', difficulty: 'beginner', points: 100, explanation: '日 (Hi / Nichi) depicts the sun with a dot in the middle.' },
  { gameType: 'kanji', question: '月', subtext: 'What does this celestial Kanji mean?', options: ['Moon / Month', 'Sun / Day', 'Tree', 'River'], correctAnswer: 'Moon / Month', difficulty: 'beginner', points: 100, explanation: '月 (Tsuki / Getsu) depicts a crescent moon.' },
  { gameType: 'kanji', question: '火', subtext: 'What does this elemental Kanji mean?', options: ['Fire', 'Water', 'Wood', 'Gold'], correctAnswer: 'Fire', difficulty: 'beginner', points: 100, explanation: '火 (Hi / Ka) depicts leaping flames of a fire.' },
  { gameType: 'kanji', question: '水', subtext: 'What does this fluid Kanji mean?', options: ['Water', 'Fire', 'Ice', 'Rain'], correctAnswer: 'Water', difficulty: 'beginner', points: 100, explanation: '水 (Mizu / Sui) represents splashing water drops.' },
  { gameType: 'kanji', question: '木', subtext: 'What does this nature Kanji mean?', options: ['Tree / Wood', 'Grass', 'Mountain', 'Field'], correctAnswer: 'Tree / Wood', difficulty: 'beginner', points: 100, explanation: '木 (Ki / Moku) depicts trunk, branches, and roots of a tree.' },
  { gameType: 'kanji', question: '金', subtext: 'What does this precious Kanji mean?', options: ['Gold / Money / Metal', 'Silver', 'Copper', 'Stone'], correctAnswer: 'Gold / Money / Metal', difficulty: 'beginner', points: 100, explanation: '金 (Kane / Kin) represents gold, metal, or money.' },
  { gameType: 'kanji', question: '土', subtext: 'What does this grounded Kanji mean?', options: ['Earth / Soil / Saturday', 'Sky', 'Mountain', 'Water'], correctAnswer: 'Earth / Soil / Saturday', difficulty: 'beginner', points: 100, explanation: '土 (Tsuchi / Do) represents a mound of soil on the ground.' },
  { gameType: 'kanji', question: '山', subtext: 'What does this majestic Kanji mean?', options: ['Mountain', 'River', 'Valley', 'Hill'], correctAnswer: 'Mountain', difficulty: 'beginner', points: 100, explanation: '山 (Yama / San) depicts the three peaks of a mountain (e.g. Fuji-san).' },
  { gameType: 'kanji', question: '川', subtext: 'What does this waterway Kanji mean?', options: ['River', 'Road', 'Sea', 'Bridge'], correctAnswer: 'River', difficulty: 'beginner', points: 100, explanation: '川 (Kawa / Sen) depicts three flowing currents of a river.' },
  { gameType: 'kanji', question: '人', subtext: 'What does this fundamental Kanji mean?', options: ['Person / Human', 'Big', 'Enter', 'Heaven'], correctAnswer: 'Person / Human', difficulty: 'beginner', points: 100, explanation: '人 (Hito / Jin) depicts two legs of a walking person.' },
  { gameType: 'kanji', question: '大', subtext: 'What does this size Kanji mean?', options: ['Big / Large', 'Small', 'Medium', 'Few'], correctAnswer: 'Big / Large', difficulty: 'beginner', points: 100, explanation: '大 (Oo / Dai) is a person standing with outstretched arms: BIG!' },
  { gameType: 'kanji', question: '小', subtext: 'What does this size Kanji mean?', options: ['Small / Little', 'Big', 'Many', 'None'], correctAnswer: 'Small / Little', difficulty: 'beginner', points: 100, explanation: '小 (Chii / Shou) represents small dividing particles.' },
  { gameType: 'kanji', question: '一, 二, 三', subtext: 'What numbers do these strokes represent?', options: ['1, 2, 3', '10, 20, 30', '4, 5, 6', 'Monday, Tuesday, Wednesday'], correctAnswer: '1, 2, 3', difficulty: 'beginner', points: 100, explanation: 'One line = 1, two lines = 2, three lines = 3.' },
  { gameType: 'kanji', question: '口', subtext: 'What bodily feature or opening does this mean?', options: ['Mouth / Opening', 'Eye', 'Box', 'Ear'], correctAnswer: 'Mouth / Opening', difficulty: 'beginner', points: 100, explanation: '口 (Kuchi / Kou) depicts an open mouth.' },

  // --- Intermediate Kanji (N4-N3 Level) ---
  { gameType: 'kanji', question: '学', subtext: 'What is the core meaning of this Kanji?', options: ['Study / Learning', 'Work', 'Rest', 'Travel'], correctAnswer: 'Study / Learning', difficulty: 'intermediate', points: 120, explanation: '学 (Gaku / Mana-bu) forms words like 学生 (Gakusei = Student).' },
  { gameType: 'kanji', question: '生', subtext: 'What does this versatile Kanji represent?', options: ['Life / Birth / Raw', 'Death', 'School', 'Time'], correctAnswer: 'Life / Birth / Raw', difficulty: 'intermediate', points: 120, explanation: '生 (Sei / I-kiru) means life or birth, as in 先生 (Sensei).' },
  { gameType: 'kanji', question: '先', subtext: 'What does this temporal Kanji mean?', options: ['Before / Ahead / Previous', 'After', 'Behind', 'Inside'], correctAnswer: 'Before / Ahead / Previous', difficulty: 'intermediate', points: 120, explanation: '先 (Saki / Sen) means before. 先生 = born before (teacher).' },
  { gameType: 'kanji', question: '国', subtext: 'What does this geopolitical Kanji mean?', options: ['Country / Nation', 'City', 'Province', 'World'], correctAnswer: 'Country / Nation', difficulty: 'intermediate', points: 120, explanation: '国 (Kuni / Koku) depicts jewels enclosed within boundaries: Country.' },
  { gameType: 'kanji', question: '車', subtext: 'What vehicle does this ancient pictograph depict?', options: ['Car / Wheel / Cart', 'Ship', 'Train', 'Horse'], correctAnswer: 'Car / Wheel / Cart', difficulty: 'intermediate', points: 120, explanation: '車 (Kuruma / Sha) depicts an axle with wheels: vehicle/car.' },
  { gameType: 'kanji', question: '電', subtext: 'What modern power does this Kanji signify?', options: ['Electricity', 'Lightning only', 'Thunder', 'Battery'], correctAnswer: 'Electricity', difficulty: 'intermediate', points: 120, explanation: '電 (Den) means electricity, as in 電車 (Densha = electric train).' },
  { gameType: 'kanji', question: '花', subtext: 'What botanical wonder does this Kanji mean?', options: ['Flower', 'Grass', 'Fruit', 'Seed'], correctAnswer: 'Flower', difficulty: 'intermediate', points: 120, explanation: '花 (Hana / Ka) means flower or blossom, as in 花見 (Hanami).' },
  { gameType: 'kanji', question: '食', subtext: 'What daily nourishment does this Kanji represent?', options: ['Eat / Food', 'Drink', 'Sleep', 'Walk'], correctAnswer: 'Eat / Food', difficulty: 'intermediate', points: 120, explanation: '食 (Ta-beru / Shoku) means to eat or food, as in 食堂 (Shokudou).' },
  { gameType: 'kanji', question: '飲', subtext: 'What consumption action does this Kanji depict?', options: ['Drink', 'Eat', 'Cook', 'Taste'], correctAnswer: 'Drink', difficulty: 'intermediate', points: 120, explanation: '飲 (No-mu / In) means to drink.' },
  { gameType: 'kanji', question: '友', subtext: 'What heartwarming relationship does this represent?', options: ['Friend / Companion', 'Enemy', 'Stranger', 'Master'], correctAnswer: 'Friend / Companion', difficulty: 'intermediate', points: 120, explanation: '友 (Tomo / Yuu) depicts two reaching hands joined in friendship.' },
  { gameType: 'kanji', question: '時', subtext: 'What measurement does this Kanji denote?', options: ['Time / Hour', 'Minute', 'Second', 'Year'], correctAnswer: 'Time / Hour', difficulty: 'intermediate', points: 120, explanation: '時 (Toki / Ji) combines Sun (日) and Temple (寺) to denote Time.' },
  { gameType: 'kanji', question: '間', subtext: 'What spatial/interval concept does this mean?', options: ['Space / Interval / Between', 'Door only', 'Sun only', 'Roof'], correctAnswer: 'Space / Interval / Between', difficulty: 'intermediate', points: 120, explanation: '間 (Aida / Ma / Kan) depicts sunlight through a doorway.' },
  { gameType: 'kanji', question: '道', subtext: 'What philosophical and physical concept is this?', options: ['Road / Way / Path', 'Bridge', 'River', 'Forest'], correctAnswer: 'Road / Way / Path', difficulty: 'intermediate', points: 120, explanation: '道 (Michi / Dou) means road or spiritual way (e.g. Judo, Shinto).' },
  { gameType: 'kanji', question: '雨', subtext: 'What weather drops fall from this Kanji?', options: ['Rain', 'Snow', 'Hail', 'Cloud'], correctAnswer: 'Rain', difficulty: 'intermediate', points: 120, explanation: '雨 (Ame / U) depicts raindrops falling under clouds.' },

  // --- Advanced Kanji (N2-N1 & Cultural Jewels) ---
  { gameType: 'kanji', question: '和', subtext: 'What profound Japanese cultural concept is this?', options: ['Harmony / Peace / Japanese Spirit', 'War', 'Chaos', 'Strictness'], correctAnswer: 'Harmony / Peace / Japanese Spirit', difficulty: 'advanced', points: 150, explanation: '和 (Wa) symbolizes harmony, gentle peace, and traditional Japanese essence (和食, 和服).' },
  { gameType: 'kanji', question: '道 (as in 茶道 or 武道)', subtext: 'In cultural arts, what does 道 signify?', options: ['The spiritual path or lifelong discipline', 'Just a physical street', 'A tournament trophy', 'An exam syllabus'], correctAnswer: 'The spiritual path or lifelong discipline', difficulty: 'advanced', points: 150, explanation: 'The "-do" suffix indicates a lifelong philosophical journey (e.g., Chado tea way, Budo martial way).' },
  { gameType: 'kanji', question: '心', subtext: 'What core human faculty does this pictograph represent?', options: ['Heart / Mind / Spirit', 'Brain only', 'Stomach', 'Lung'], correctAnswer: 'Heart / Mind / Spirit', difficulty: 'advanced', points: 150, explanation: '心 (Kokoro / Shin) represents the heart, soul, and emotional mind.' },
  { gameType: 'kanji', question: '桜', subtext: 'What beloved cherry bloom Kanji is this?', options: ['Sakura / Cherry Blossom', 'Lotus', 'Chrysanthemum', 'Iris'], correctAnswer: 'Sakura / Cherry Blossom', difficulty: 'advanced', points: 150, explanation: '桜 (Sakura / Ou) is the cherished cherry blossom.' },
  { gameType: 'kanji', question: '夢', subtext: 'What nocturnal vision or life aspiration is this?', options: ['Dream / Vision', 'Reality', 'Sleep', 'Nightmare'], correctAnswer: 'Dream / Vision', difficulty: 'advanced', points: 150, explanation: '夢 (Yume / Mu) means dream or aspiration.' },
  { gameType: 'kanji', question: '光', subtext: 'What radiant phenomenon does this Kanji represent?', options: ['Light / Ray / Radiance', 'Darkness', 'Fire', 'Shadow'], correctAnswer: 'Light / Ray / Radiance', difficulty: 'advanced', points: 150, explanation: '光 (Hikari / Kou) means light or radiance.' },
  { gameType: 'kanji', question: '旅', subtext: 'What wanderer\'s Kanji is this?', options: ['Travel / Journey', 'Stay', 'Flight', 'Work'], correctAnswer: 'Travel / Journey', difficulty: 'advanced', points: 150, explanation: '旅 (Tabi / Ryo) means voyage or journey, as in 旅人 (traveler).' },
  { gameType: 'kanji', question: '愛', subtext: 'What timeless emotion does this Kanji embody?', options: ['Love / Affection', 'Courage', 'Patience', 'Honesty'], correctAnswer: 'Love / Affection', difficulty: 'advanced', points: 150, explanation: '愛 (Ai) combines heart (心) wrapped in caring grace: Love.' },
  { gameType: 'kanji', question: '武', subtext: 'What warrior tradition does this Kanji anchor?', options: ['Military / Martial / Chivalry', 'Music', 'Poetry', 'Agriculture'], correctAnswer: 'Military / Martial / Chivalry', difficulty: 'advanced', points: 150, explanation: '武 (Bu / Mu) forms 武士 (Bushi = Samurai warrior).' },
  { gameType: 'kanji', question: '士', subtext: 'What gentleman or warrior rank does this mean?', options: ['Scholar / Gentleman / Samurai', 'Farmer', 'Merchant', 'Apprentice'], correctAnswer: 'Scholar / Gentleman / Samurai', difficulty: 'advanced', points: 150, explanation: '士 (Shi) denotes a distinguished gentleman or samurai.' },
  { gameType: 'kanji', question: '城', subtext: 'What historic fortress Kanji is this?', options: ['Castle / Fortress', 'Shrine', 'Palace', 'Tower'], correctAnswer: 'Castle / Fortress', difficulty: 'advanced', points: 150, explanation: '城 (Shiro / Jou) means Japanese castle (e.g. Himeji-jou).' },
  { gameType: 'kanji', question: '神', subtext: 'What divine Shinto or spiritual entity is this?', options: ['God / Deity / Spirit (Kami)', 'Ghost', 'Hero', 'Emperor'], correctAnswer: 'God / Deity / Spirit (Kami)', difficulty: 'advanced', points: 150, explanation: '神 (Kami / Shin) refers to Shinto spirits or deities.' },
  { gameType: 'kanji', question: '鳥居', subtext: 'What iconic sacred gate at Shinto shrines is this?', options: ['Torii Gate', 'Castle Moat', 'Pagoda Roof', 'Garden Bridge'], correctAnswer: 'Torii Gate', difficulty: 'advanced', points: 150, explanation: '鳥居 (Torii) literally translates to "bird perch", the sacred boundary gate.' },
  { gameType: 'kanji', question: '富士山', subtext: 'Read and translate this legendary geographic landmark', options: ['Mount Fuji', 'Mount Everest', 'Mount Aso', 'Mount Hiei'], correctAnswer: 'Mount Fuji', difficulty: 'advanced', points: 150, explanation: '富士山 (Fuji-san) is Japan\'s sacred 3,776-meter peak.' },
];

// ==========================================
// 4. JAPANESE CULTURE CHALLENGE (30 questions)
// ==========================================
export const CULTURE_QUESTIONS: Omit<IQuestion, 'id'>[] = [
  {
    gameType: 'culture',
    question: 'What is the traditional Japanese formal floor-length garment with wide sleeves called?',
    subtext: 'Traditional Clothing & Textiles',
    options: ['Kimono (着物)', 'Yukata (浴衣)', 'Hakama (袴)', 'Jinbei (甚平)'],
    correctAnswer: 'Kimono (着物)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'The Kimono (literally "thing to wear") is the iconic traditional Japanese garment worn on formal occasions.',
  },
  {
    gameType: 'culture',
    question: 'What is the lightweight, casual cotton robe commonly worn at summer festivals and onsen (hot springs)?',
    subtext: 'Summer Tradition',
    options: ['Yukata', 'Kimono', 'Haori', 'Chouji'],
    correctAnswer: 'Yukata',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Yukata (浴衣) are airy unlined cotton robes perfect for summer fireworks and hot spring relaxation.',
  },
  {
    gameType: 'culture',
    question: 'What is the vermilion (red-orange) gate that marks the entrance to a Shinto shrine called?',
    subtext: 'Architecture & Spirituality',
    options: ['Torii (鳥居)', 'Mon (門)', 'Pagoda (塔)', 'Shourou (鐘楼)'],
    correctAnswer: 'Torii (鳥居)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'A Torii gate marks the sacred threshold between the mundane world and the sacred domain of the Kami.',
  },
  {
    gameType: 'culture',
    question: 'What is the Japanese art of paper folding called?',
    subtext: 'Traditional Crafts',
    options: ['Origami (折り紙)', 'Ikebana (生け花)', 'Shodo (書道)', 'Kirigami (切り紙)'],
    correctAnswer: 'Origami (折り紙)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Origami (ori = fold, kami = paper) is the worldwide revered craft of transforming paper into cranes, flowers, and geometric art.',
  },
  {
    gameType: 'culture',
    question: 'What is the traditional Japanese art of flower arrangement known as?',
    subtext: 'Aesthetic Disciplines',
    options: ['Ikebana (生け花)', 'Bonsai (盆栽)', 'Kintsugi (金継ぎ)', 'Origami (折り紙)'],
    correctAnswer: 'Ikebana (生け花)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Ikebana (also known as Kado, the way of flowers) emphasizes balance, minimalism, and natural rhythm.',
  },
  {
    gameType: 'culture',
    question: 'What is the art of repairing broken pottery with golden lacquer to celebrate imperfections?',
    subtext: 'Wabi-Sabi Aesthetics',
    options: ['Kintsugi (金継ぎ)', 'Urushi (漆)', 'Makie (蒔絵)', 'Raku (楽焼)'],
    correctAnswer: 'Kintsugi (金継ぎ)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Kintsugi highlights cracks with gold, embracing history and the philosophy of wabi-sabi (beauty in imperfection).',
  },
  {
    gameType: 'culture',
    question: 'What is the ceremonial preparation and presentation of powdered green tea called?',
    subtext: 'Tea Culture',
    options: ['Chado / Sado (茶道)', 'Sencha (煎茶)', 'Kyusu (急須)', 'Matcha-kai (抹茶会)'],
    correctAnswer: 'Chado / Sado (茶道)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Chado (The Way of Tea), perfected by Sen no Rikyu, centers on harmony (wa), respect (kei), purity (sei), and tranquility (jaku).',
  },
  {
    gameType: 'culture',
    question: 'What is the spring custom of viewing cherry blossoms and picnicking beneath the petals?',
    subtext: 'Seasonal Customs',
    options: ['Hanami (花見)', 'Momijigari (紅葉狩り)', 'Tsukimi (月見)', 'Matsuri (祭り)'],
    correctAnswer: 'Hanami (花見)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Hanami ("flower viewing") brings friends and families together under blooming sakura trees across Japan.',
  },
  {
    gameType: 'culture',
    question: 'What is the Star Festival celebrated on July 7th, where people write wishes on colorful paper strips (Tanzaku)?',
    subtext: 'Festivals (Matsuri)',
    options: ['Tanabata (七夕)', 'Obon (お盆)', 'Setsubun (節分)', 'Hinamatsuri (雛祭り)'],
    correctAnswer: 'Tanabata (七夕)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Tanabata celebrates the once-a-year romantic reunion of celestial lovers Orihime and Hikoboshi across the Milky Way.',
  },
  {
    gameType: 'culture',
    question: 'What is the February ritual where people throw roasted soybeans shouting "Oni wa soto! Fuku wa uchi!" (Demons out! Fortune in!)?',
    subtext: 'Seasonal Customs',
    options: ['Setsubun (節分)', 'Kodomo no Hi (こどもの日)', 'Shichi-Go-San (七五三)', 'Seijin no Hi (成人の日)'],
    correctAnswer: 'Setsubun (節分)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Setsubun marks the eve of spring with bean-scattering (Mamemaki) to banish winter evil spirits and welcome blessings.',
  },
  {
    gameType: 'culture',
    question: 'What is the festival on March 3rd featuring ornate tiered doll displays representing the Heian imperial court?',
    subtext: 'Traditional Celebrations',
    options: ['Hinamatsuri (Doll Festival / 雛祭り)', 'Tango no Sekku', 'Bunka no Hi', 'Showa no Hi'],
    correctAnswer: 'Hinamatsuri (Doll Festival / 雛祭り)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Hinamatsuri prays for the health and prosperity of young girls, displaying traditional Hina dolls.',
  },
  {
    gameType: 'culture',
    question: 'What is the round hollow papier-mâché doll with one eye painted when setting a goal and the other when achieved?',
    subtext: 'Good Luck Charms',
    options: ['Daruma (達磨)', 'Maneki-neko (招き猫)', 'Kokeshi (こけし)', 'Omamori (お守り)'],
    correctAnswer: 'Daruma (達磨)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Daruma dolls symbolize perseverance: paint one eye when making a resolution, and fill the second when accomplished!',
  },
  {
    gameType: 'culture',
    question: 'What is the popular ceramic "Beckoning Cat" figurine believed to attract good luck and customers to shops?',
    subtext: 'Good Luck Charms',
    options: ['Maneki-neko (招き猫)', 'Inu Hariko', 'Tanuki statue', 'Akabeko'],
    correctAnswer: 'Maneki-neko (招き猫)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Maneki-neko beckons with its raised paw to welcome prosperity, good fortune, and visitors.',
  },
  {
    gameType: 'culture',
    question: 'What are the sacred amulets sold at Shinto shrines and Buddhist temples for safety and protection called?',
    subtext: 'Spiritual Talismans',
    options: ['Omamori (お守り)', 'Ofuda (御札)', 'Ema (絵馬)', 'Omikuji (おみくじ)'],
    correctAnswer: 'Omamori (お守り)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Omamori are brocade fabric pouches containing sacred blessings for traffic safety, academic success, health, and love.',
  },
  {
    gameType: 'culture',
    question: 'What are the small wooden plaques where shrine visitors write wishes and prayers called?',
    subtext: 'Shrine Traditions',
    options: ['Ema (絵馬)', 'Omikuji (おみくじ)', 'Shide (紙垂)', 'Shimenawa (注連縄)'],
    correctAnswer: 'Ema (絵馬)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Ema (literally "picture horse") hang in vibrant racks outside shrines displaying hopes and gratitude.',
  },
  {
    gameType: 'culture',
    question: 'What is Japan\'s ancient national martial art featuring heavyweight wrestlers inside a sacred sand ring (Dohyo)?',
    subtext: 'Martial Arts & Sports',
    options: ['Sumo (相撲)', 'Judo (柔道)', 'Kendo (剣道)', 'Karate (空手)'],
    correctAnswer: 'Sumo (相撲)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Sumo dates back over 1,500 years with ancient Shinto purification rituals, salt throwing, and sacred referee attire.',
  },
  {
    gameType: 'culture',
    question: 'What is the ancient code of ethics and honor followed by samurai warriors called?',
    subtext: 'Samurai Heritage',
    options: ['Bushido (武士道)', 'Shinshindo', 'Ronin-kai', 'Katana-do'],
    correctAnswer: 'Bushido (武士道)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Bushido ("The Way of the Warrior") dictates righteousness, courage, benevolence, respect, honesty, honor, and loyalty.',
  },
  {
    gameType: 'culture',
    question: 'What is the Japanese practice of forest bathing, immersing in nature for therapeutic benefits, called?',
    subtext: 'Wellness & Nature',
    options: ['Shinrin-yoku (森林浴)', 'Hanami', 'Misogi', 'Zazen'],
    correctAnswer: 'Shinrin-yoku (森林浴)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Shinrin-yoku ("forest bathing") is scientifically recognized for lowering cortisol and boosting immunity through trees\' natural phytoncides.',
  },
  {
    gameType: 'culture',
    question: 'Before entering a traditional Japanese home, ryokan, or temple tatami room, what must you always do?',
    subtext: 'Cultural Etiquette',
    options: ['Take off your outdoor shoes', 'Clap three times', 'Bow to the floor', 'Turn off all lights'],
    correctAnswer: 'Take off your outdoor shoes',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Remove your outdoor shoes at the genkan (sunken entryway) and switch into provided slippers to maintain interior purity.',
  },
  {
    gameType: 'culture',
    question: 'What should you NEVER do with your chopsticks (hashi) according to Japanese dining etiquette?',
    subtext: 'Dining Customs',
    options: ['Stick them vertically into a bowl of rice', 'Place them on a chopstick rest (hashioki)', 'Hold them in one hand', 'Use both together to pick up sushi'],
    correctAnswer: 'Stick them vertically into a bowl of rice',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Sticking chopsticks upright (Tsukitate-bashi) resembles incense bowls at Buddhist funerals and is considered taboo.',
  },
  {
    gameType: 'culture',
    question: 'What are traditional Japanese woven straw floor mats called?',
    subtext: 'Traditional Architecture',
    options: ['Tatami (畳)', 'Shoji (障子)', 'Fusuma (襖)', 'Tokonoma (床の間)'],
    correctAnswer: 'Tatami (畳)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Tatami mats woven from rush grass provide springy comfort, fresh herbal aroma, and serve as standard Japanese room measurements.',
  },
  {
    gameType: 'culture',
    question: 'What are translucent sliding paper screens that diffuse soft light in traditional Japanese rooms called?',
    subtext: 'Traditional Architecture',
    options: ['Shoji (障子)', 'Fusuma (襖)', 'Noren (暖簾)', 'Sudare (すだれ)'],
    correctAnswer: 'Shoji (障子)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Shoji are lightweight wooden lattice doors backed with translucent washi paper that filter gentle ambient daylight.',
  },
  {
    gameType: 'culture',
    question: 'What is the fabric split curtain hung at the doorway of Japanese shops and restaurants called?',
    subtext: 'Street Architecture',
    options: ['Noren (暖簾)', 'Chochin (提灯)', 'Tenugui (手ぬぐい)', 'Furoshiki (風呂敷)'],
    correctAnswer: 'Noren (暖簾)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Noren curtains signal when a shop is open for business and display the family crest or specialty dish.',
  },
  {
    gameType: 'culture',
    question: 'What is the versatile Japanese wrapping cloth used for gifts, bento boxes, and luggage since ancient times?',
    subtext: 'Sustainable Traditions',
    options: ['Furoshiki (風呂敷)', 'Tenugui (手ぬぐい)', 'Sensu (扇子)', 'Obi (帯)'],
    correctAnswer: 'Furoshiki (風呂敷)',
    difficulty: 'intermediate',
    points: 120,
    explanation: 'Furoshiki is an eco-friendly cloth folded into elegant carriers for bottles, groceries, gifts, and books.',
  },
  {
    gameType: 'culture',
    question: 'What is the summer street food of spherical batter balls stuffed with minced octopus called?',
    subtext: 'Street Food & Kansai Cuisine',
    options: ['Takoyaki (たこ焼き)', 'Okonomiyaki (お好み焼き)', 'Taiyaki (たい焼き)', 'Yakitori (焼き鳥)'],
    correctAnswer: 'Takoyaki (たこ焼き)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Takoyaki is Osaka\'s world-famous sizzling octopus dumplings brushed with savory glaze, mayo, and bonito flakes.',
  },
  {
    gameType: 'culture',
    question: 'What is the fish-shaped sweet pastry typically stuffed with sweet red bean paste (Azuki) or custard?',
    subtext: 'Traditional Sweets',
    options: ['Taiyaki (たい焼き)', 'Dorayaki (どら焼き)', 'Dango (団子)', 'Daifuku (大福)'],
    correctAnswer: 'Taiyaki (たい焼き)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Taiyaki resembles the sea bream (Tai), a symbol of good luck and celebration in Japanese folklore.',
  },
  {
    gameType: 'culture',
    question: 'What is the traditional Japanese lunchbox artfully packed with balanced, colorful portions called?',
    subtext: 'Food Culture',
    options: ['Bento (弁当)', 'Ekiben (駅弁)', 'Teishoku (定食)', 'Kaiseki (懐石)'],
    correctAnswer: 'Bento (弁当)',
    difficulty: 'beginner',
    points: 100,
    explanation: 'Bento boxes reflect visual harmony, balance, and seasonal flavor combinations.',
  },
  {
    gameType: 'culture',
    question: 'What is the Japanese concept of wholeheartedly anticipating guests\' needs with warmth and selflessness?',
    subtext: 'Hospitality',
    options: ['Omotenashi (おもてなし)', 'Gaman (我慢)', 'Mottainai (もったいない)', 'Komorebi (木漏れ日)'],
    correctAnswer: 'Omotenashi (おもてなし)',
    difficulty: 'advanced',
    points: 150,
    explanation: 'Omotenashi is Japan\'s legendary hospitality—providing impeccable care without expecting tips.',
  },
  {
    gameType: 'culture',
    question: 'What is the Japanese cultural virtue of persevering through difficulty with dignity and patience?',
    subtext: 'Cultural Mindset',
    options: ['Gaman (我慢)', 'Shoshin (初心)', 'Kaizen (改善)', 'Wabi-Sabi'],
    correctAnswer: 'Gaman (我慢)',
    difficulty: 'advanced',
    points: 150,
    explanation: 'Gaman reflects inner strength, patience, and resilience in the face of sudden hardship or natural disaster.',
  },
  {
    gameType: 'culture',
    question: 'What poetic Japanese word describes sunlight filtering through the leaves of trees?',
    subtext: 'Untranslatable Aesthetic Words',
    options: ['Komorebi (木漏れ日)', 'Yugen (幽玄)', 'Mono no Aware (もののあわれ)', 'Ikigai (生きがい)'],
    correctAnswer: 'Komorebi (木漏れ日)',
    difficulty: 'advanced',
    points: 150,
    explanation: 'Komorebi captures the shimmering dance of sunlight through leafy forest canopies.',
  },
];

// ==========================================
// 5. JAPAN EXPLORER DESTINATIONS (10 Iconic Locations)
// ==========================================
export const DESTINATIONS_DATA: IDestination[] = [
  {
    id: 'tokyo',
    nameJa: '東京',
    nameEn: 'Tokyo',
    region: 'Kanto',
    coordinates: { x: 74, y: 55 },
    tagline: 'Futuristic metropolis where neon skyscape meets timeless heritage',
    famousFor: ['Shibuya Crossing', 'Sensō-ji Temple in Asakusa', 'Akihabara Tech Town', 'Tokyo Skytree'],
    traditionalFood: 'Edomae Nigiri Sushi, Monjayaki, and Tsukiji Seafood Bowls',
    culture: 'Hyper-modern innovation harmonized with historic shrine districts and cutting-edge fashion.',
    interestingFact: 'Shibuya Crossing is crossed by over 3,000 pedestrians in a single green light during peak rush hour!',
    japanesePhrase: {
      japanese: '東京へようこそ！',
      romaji: 'Toukyou e youkoso!',
      english: 'Welcome to Tokyo!',
    },
    pointsAwarded: 25,
  },
  {
    id: 'kyoto',
    nameJa: '京都',
    nameEn: 'Kyoto',
    region: 'Kansai',
    coordinates: { x: 57, y: 59 },
    tagline: "Japan's thousand-year cultural heart and soul",
    famousFor: ['Fushimi Inari 10,000 Torii Gates', 'Kinkaku-ji (Golden Pavilion)', 'Gion Geisha District', 'Arashiyama Bamboo Grove'],
    traditionalFood: 'Kaiseki Ryori, Matcha sweets, Yudofu (tofu hot pot)',
    culture: 'Home to 17 UNESCO World Heritage sites, wooden Machiya townhouses, and pristine Zen stone gardens.',
    interestingFact: 'Kyoto served as Japan\'s imperial capital for over a millennium from 794 until 1868.',
    japanesePhrase: {
      japanese: 'おいでやす',
      romaji: 'Oideyasu',
      english: 'Welcome (Kyoto traditional dialect)',
    },
    pointsAwarded: 25,
  },
  {
    id: 'osaka',
    nameJa: '大阪',
    nameEn: 'Osaka',
    region: 'Kansai',
    coordinates: { x: 53, y: 62 },
    tagline: "Japan's kitchen and comedy capital",
    famousFor: ['Dotonbori Glico Running Man', 'Osaka Castle', 'Shinsekai & Tsutenkaku Tower', 'Universal Studios Japan'],
    traditionalFood: 'Takoyaki (octopus balls), Okonomiyaki, Kushikatsu',
    culture: 'Famous for its warm, humorous locals, vibrant nightlife, and food-loving spirit of Kuidaore (eat until you drop).',
    interestingFact: 'Osaka merchant culture developed the lively, fast-paced Manzai double-act comedy beloved across Japan.',
    japanesePhrase: {
      japanese: 'おおきに！',
      romaji: 'Oookini!',
      english: 'Thank you very much! (Osaka dialect)',
    },
    pointsAwarded: 25,
  },
  {
    id: 'fuji',
    nameJa: '富士山',
    nameEn: 'Mount Fuji',
    region: 'Chubu / Shizuoka & Yamanashi',
    coordinates: { x: 70, y: 58 },
    tagline: 'Sacred symmetrical volcanic summit and artistic muse',
    famousFor: ['Fuji Five Lakes (Kawaguchiko)', 'Chureito Pagoda View', 'Subaru Line 5th Station', 'Hakone Hot Springs'],
    traditionalFood: 'Hoto noodles, Mount Fuji spring water soba, Shizuoka Green Tea',
    culture: 'Recognized as a UNESCO Cultural World Heritage site for inspiring centuries of ukiyo-e woodblock prints and poetry.',
    interestingFact: 'Mount Fuji stands at 3,776 meters high and is an active volcano with its last eruption occurring in 1707.',
    japanesePhrase: {
      japanese: '素晴らしい景色ですね！',
      romaji: 'Subarashii keshiki desu ne!',
      english: 'What a magnificent view!',
    },
    pointsAwarded: 25,
  },
  {
    id: 'hiroshima',
    nameJa: '広島',
    nameEn: 'Hiroshima',
    region: 'Chugoku',
    coordinates: { x: 38, y: 64 },
    tagline: 'City of global peace, resilient beauty, and floating shrines',
    famousFor: ['Miyajima Floating Torii Gate (Itsukushima)', 'Peace Memorial Park & A-Bomb Dome', 'Hiroshima Castle'],
    traditionalFood: 'Hiroshima-style layered Okonomiyaki, grilled Seto Inland Sea oysters, Momiji Manju cakes',
    culture: 'A global symbol of everlasting peace, hope, and cultural regeneration surrounded by the tranquil Seto Inland Sea.',
    interestingFact: 'The friendly wild deer of Miyajima island freely wander the streets and beaches right beside visitors!',
    japanesePhrase: {
      japanese: '平和を祈ります',
      romaji: 'Heiwa wo inorimasu',
      english: 'Wishing for world peace',
    },
    pointsAwarded: 25,
  },
  {
    id: 'hokkaido',
    nameJa: '北海道',
    nameEn: 'Hokkaido',
    region: 'Hokkaido',
    coordinates: { x: 84, y: 22 },
    tagline: 'Northern wilderness of powder snow, lavender fields, and dairy paradise',
    famousFor: ['Sapporo Snow Festival', 'Niseko Ski Slopes', 'Furano Flower Fields', 'Otaru Canal'],
    traditionalFood: 'Miso Ramen, Genghis Khan mutton BBQ, Hokkaido Soft Serve ice cream, King Crab',
    culture: 'Vast dramatic national parks, rich Indigenous Ainu heritage, and crisp alpine seasons.',
    interestingFact: 'Hokkaido produces more than 50% of all of Japan\'s delicious fresh milk and dairy butter!',
    japanesePhrase: {
      japanese: 'なまら美味しい！',
      romaji: 'Namara oishii!',
      english: 'Super delicious! (Hokkaido dialect)',
    },
    pointsAwarded: 25,
  },
  {
    id: 'okinawa',
    nameJa: '沖縄',
    nameEn: 'Okinawa',
    region: 'Kyushu & Okinawa',
    coordinates: { x: 18, y: 88 },
    tagline: 'Subtropical paradise of turquoise waters, Ryukyu castles, and longevity',
    famousFor: ['Shurijo Castle', 'Kerama Coral Islands', 'Churaumi Aquarium', 'Cape Manzamo'],
    traditionalFood: 'Okinawa Soba, Goya Champuru (bitter melon stir-fry), Rafute braised pork belly, Umibudo sea grapes',
    culture: 'Unique Ryukyu Kingdom heritage, distinct music played on the snake-skin Sanshin, and world-renowned centenarian longevity.',
    interestingFact: 'Karate was originally created and developed in Okinawa before spreading across the globe!',
    japanesePhrase: {
      japanese: 'はいさい！めんそーれ！',
      romaji: 'Haisai! Mensoore!',
      english: 'Hello! Welcome! (Okinawan Uchinaaguchi)',
    },
    pointsAwarded: 25,
  },
  {
    id: 'nara',
    nameJa: '奈良',
    nameEn: 'Nara',
    region: 'Kansai',
    coordinates: { x: 58, y: 64 },
    tagline: "Ancient cradle of Japanese Buddhism and sacred bowing deer",
    famousFor: ['Todai-ji Great Bronze Buddha (Daibutsu)', 'Nara Park Deer', 'Kasuga Taisha Lantern Shrine', 'Horyu-ji (world\'s oldest wooden buildings)'],
    traditionalFood: 'Kaki no Ha Zushi (persimmon leaf-wrapped sushi), Miwa somen noodles',
    culture: 'Japan\'s first permanent imperial capital (Heijo-kyo, 710 AD) where Shinto and Buddhist architectures flourish side by side.',
    interestingFact: 'Over 1,200 free-roaming deer in Nara Park are protected as natural monuments and will politely bow for a deer cracker (Shika Senbei)!',
    japanesePhrase: {
      japanese: '鹿せんべいをあげましょう',
      romaji: 'Shika senbei wo agemashou',
      english: "Let's feed the deer crackers",
    },
    pointsAwarded: 25,
  },
  {
    id: 'kanazawa',
    nameJa: '金沢',
    nameEn: 'Kanazawa',
    region: 'Hokuriku',
    coordinates: { x: 61, y: 48 },
    tagline: 'Artisan haven of gold leaf, preserved samurai quarters, and master gardens',
    famousFor: ['Kenroku-en (One of Japan\'s Three Great Gardens)', 'Nagamachi Samurai District', 'Higashi Chaya Tea District', '21st Century Contemporary Art Museum'],
    traditionalFood: 'Kano Crab, Gold-leaf ice cream, Jibu-ni stew',
    culture: 'Producing over 99% of Japan\'s gold leaf, Kanazawa rivaled Kyoto in Edo-period craftsmanship and tea heritage.',
    interestingFact: 'You can eat real 24-karat gold leaf wrapped around creamy matcha soft serve in Kanazawa!',
    japanesePhrase: {
      japanese: '金箔ソフトクリームは絶品です',
      romaji: 'Kinpaku sofuto kuriimu wa zeppin desu',
      english: 'The gold leaf soft serve is exquisite',
    },
    pointsAwarded: 25,
  },
  {
    id: 'hakone',
    nameJa: '箱根',
    nameEn: 'Hakone',
    region: 'Kanto',
    coordinates: { x: 72, y: 60 },
    tagline: 'Legendary hot spring sanctuary nestled beside Mount Fuji',
    famousFor: ['Lake Ashi Pirate Sightseeing Ship', 'Owakudani Volcanic Sulphur Valley', 'Hakone Open-Air Museum', 'Hakone Tozan Mountain Switchback Railway'],
    traditionalFood: 'Kuro-tamago (black eggs boiled in volcanic hot springs), Hakone Soba, Tofu Cuisine',
    culture: 'Beloved restorative mountain retreat on the historic Tokaido highway since the Edo period.',
    interestingFact: 'Eating one Owakudani black egg (boiled in volcanic mineral springs) is said by legend to add seven years to your life!',
    japanesePhrase: {
      japanese: '温泉で温まりましょう',
      romaji: 'Onsen de atatamarimashou',
      english: "Let's warm up in the hot springs",
    },
    pointsAwarded: 25,
  },
];

// ==========================================
// 6. MYSTERY CODE CHALLENGES (10 levels of decoding)
// ==========================================
export const MYSTERY_CHALLENGES: IMysteryClue[] = [
  {
    id: 'mystery-1',
    stage: 1,
    title: 'Clue 1: The Spring Blossom Cipher',
    japaneseText: 'さくら',
    romajiText: 'SA-KU-RA',
    hint: 'Deconstruct the three hiragana syllables: さ (sa) + く (ku) + ら (ra). What cherished springtime bloom does this reveal?',
    decodedMeaning: 'Cherry Blossom (Sakura)',
    options: ['Cherry Blossom (Sakura)', 'Green Tea (Ocha)', 'Mount Fuji (Fuji-san)', 'Paper Crane (Tsuru)'],
    storyText: 'The pink petal winds carry the first ancient seal open. The gates of the AI Lab awaken!',
  },
  {
    id: 'mystery-2',
    stage: 2,
    title: 'Clue 2: The Sacred Mountain Code',
    japaneseText: 'ふじさん',
    romajiText: 'FU-JI-SA-N',
    hint: 'Decode the four characters: ふ (fu) + じ (ji) + さ (sa) + ん (n). What 3,776-meter sacred peak is this?',
    decodedMeaning: 'Mount Fuji (Fujisan)',
    options: ['Mount Fuji (Fujisan)', 'Tokyo Tower', 'Golden Pavilion', 'Great Buddha'],
    storyText: 'A silhouette of snow-capped majesty rises through the mist. The mountain spirit grants passage!',
  },
  {
    id: 'mystery-3',
    stage: 3,
    title: 'Clue 3: The Warrior Honor Inscription',
    japaneseText: 'さむらい',
    romajiText: 'SA-MU-RA-I',
    hint: 'Decode the legendary warrior title: さ (sa) + む (mu) + ら (ra) + い (i).',
    decodedMeaning: 'Samurai (Bushi)',
    options: ['Samurai (Bushi)', 'Ninja (Shinobi)', 'Shogun (General)', 'Monk (Sohei)'],
    storyText: 'A gleaming katana reflects the moonlit night. Bushido wisdom flows into your cipher book!',
  },
  {
    id: 'mystery-4',
    stage: 4,
    title: 'Clue 4: The Shadow Messenger',
    japaneseText: 'にんじゃ',
    romajiText: 'NI-N-JYA',
    hint: 'Decode the three sounds: に (ni) + ん (n) + じゃ (jya). Master of stealth and camouflage!',
    decodedMeaning: 'Ninja (Shinobi)',
    options: ['Ninja (Shinobi)', 'Ronin (Wanderer)', 'Geisha (Artist)', 'Kabuki Actor'],
    storyText: 'Smoke swirls silently across the tatami floor! The shadow operative leaves behind a cryptogram.',
  },
  {
    id: 'mystery-5',
    stage: 5,
    title: 'Clue 5: The Sacred Fox Spirit',
    japaneseText: 'きつね',
    romajiText: 'KI-TSU-NE',
    hint: 'Decode the three syllables: き (ki) + つ (tsu) + ね (ne). Messenger of the Shinto rice deity Inari!',
    decodedMeaning: 'Kitsune (Fox)',
    options: ['Kitsune (Fox)', 'Tanuki (Raccoon Dog)', 'Tsuru (Crane)', 'Koi (Carp)'],
    storyText: 'A golden fox with a flame-tipped tail bows respectfully at the shrine torii. The path deepens!',
  },
  {
    id: 'mystery-6',
    stage: 6,
    title: 'Clue 6: The Harmony of Nature and Tea',
    japaneseText: 'ちゃどう',
    romajiText: 'CHA-DO-U',
    hint: 'Decode: ちゃ (cha = tea) + どう (dou = way / discipline).',
    decodedMeaning: 'The Way of Tea (Tea Ceremony)',
    options: ['The Way of Tea (Tea Ceremony)', 'Flower Arrangement (Ikebana)', 'Calligraphy (Shodo)', 'Sword Fighting (Kendo)'],
    storyText: 'A whisk of powdered emerald matcha froths into a bowl of pure tranquility. Wa, Kei, Sei, Jaku!',
  },
  {
    id: 'mystery-7',
    stage: 7,
    title: 'Clue 7: The Land of the Rising Sun',
    japaneseText: 'にっぽん',
    romajiText: 'NI-P-PO-N',
    hint: 'Decode: に (ni) + small っ (double p) + ぽ (po) + ん (n). What country\'s authentic native name is this?',
    decodedMeaning: 'Nippon / Nihon (Japan)',
    options: ['Nippon / Nihon (Japan)', 'Tokyo Metropolis', 'Kyoto Capital', 'Asia Continent'],
    storyText: 'The morning sun casts crimson warmth across the islands. The pulse of Japan resonates!',
  },
  {
    id: 'mystery-8',
    stage: 8,
    title: 'Clue 8: The Thousand Paper Wish',
    japaneseText: 'せんばづる',
    romajiText: 'SE-N-BA-ZU-RU',
    hint: 'Decode: せん (sen = 1000) + ば (ba = birds) + づる (zuru = cranes). Folded for peace and recovery.',
    decodedMeaning: 'One Thousand Origami Cranes',
    options: ['One Thousand Origami Cranes', 'Golden Dragon Scroll', 'Cherry Blossom Festival', 'Temple Bell Chime'],
    storyText: 'One thousand rainbow paper cranes flutter toward the sky carrying wishes of healing and peace.',
  },
  {
    id: 'mystery-9',
    stage: 9,
    title: 'Clue 9: The Pure Spirit of Hospitality',
    japaneseText: 'おもてなし',
    romajiText: 'O-MO-TE-NA-SHI',
    hint: 'Decode the five syllables: お (o) + も (mo) + て (te) + な (na) + し (shi). Heartfelt Japanese hospitality.',
    decodedMeaning: 'Omotenashi (Selfless Hospitality)',
    options: ['Omotenashi (Selfless Hospitality)', 'Itadakimasu (Gratitude)', 'Sayounara (Farewell)', 'Gochisousama (Feast)'],
    storyText: 'Every detail in the room anticipates your comfort before you even speak. The master vault unlocks!',
  },
  {
    id: 'mystery-10',
    stage: 10,
    title: 'FINAL SEAL: 🔐 THE SECRET JAPAN CODE',
    japaneseText: 'にほんご えーあい らぼ (日本語AIラボ)',
    romajiText: 'NI-HO-N-GO  E-I  A-I  RA-BO',
    hint: 'Combine all decoded knowledge: 日本語 (Japanese Language) + AI + ラボ (Lab). What is this grand college expo journey called?',
    decodedMeaning: 'NIHONGO AI LAB (日本語 AI ラボ)',
    options: ['NIHONGO AI LAB (日本語 AI ラボ)', 'Tokyo Game Arcade', 'Kyoto Imperial Museum', 'Mount Fuji Cyber Portal'],
    storyText: '🎉 CONGRATULATIONS! You have unlocked the ultimate treasure of NIHONGO AI LAB! The secret code of language, culture, and friendship shines bright in the hall of champions!',
  },
];

// ==========================================
// 7. REALISTIC SEED LEADERBOARD PLAYERS (16 players)
// ==========================================
export const SEED_PLAYERS: IPlayer[] = [
  {
    id: 'player-haruto',
    nickname: 'Haruto',
    avatar: 'samurai',
    totalPoints: 8450,
    level: 18,
    gamesPlayed: 24,
    bestStreak: 12,
    accuracy: 96,
    badges: ['sakura_starter', 'hiragana_hero', 'kanji_master', 'japan_explorer', 'streak_samurai', 'expo_champion'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'player-sakura',
    nickname: 'Sakura',
    avatar: 'sakura',
    totalPoints: 8120,
    level: 17,
    gamesPlayed: 22,
    bestStreak: 14,
    accuracy: 94,
    badges: ['sakura_starter', 'hiragana_hero', 'word_warrior', 'mystery_solver', 'streak_samurai', 'expo_champion'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'player-kishore',
    nickname: 'Kishore',
    avatar: 'kitsune',
    totalPoints: 7980,
    level: 16,
    gamesPlayed: 20,
    bestStreak: 11,
    accuracy: 92,
    badges: ['sakura_starter', 'hiragana_hero', 'word_warrior', 'kanji_master', 'japan_explorer', 'streak_samurai'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'player-akira',
    nickname: 'Akira',
    avatar: 'ninja',
    totalPoints: 7640,
    level: 15,
    gamesPlayed: 19,
    bestStreak: 10,
    accuracy: 90,
    badges: ['sakura_starter', 'hiragana_hero', 'mystery_solver', 'streak_samurai'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'player-yuki',
    nickname: 'Yuki',
    avatar: 'fuji',
    totalPoints: 7220,
    level: 14,
    gamesPlayed: 18,
    bestStreak: 9,
    accuracy: 91,
    badges: ['sakura_starter', 'hiragana_hero', 'word_warrior', 'japan_explorer'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'player-ren',
    nickname: 'Ren',
    avatar: 'tanuki',
    totalPoints: 6850,
    level: 13,
    gamesPlayed: 16,
    bestStreak: 8,
    accuracy: 89,
    badges: ['sakura_starter', 'hiragana_hero', 'kanji_master'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 'player-hana',
    nickname: 'Hana',
    avatar: 'sakura',
    totalPoints: 6310,
    level: 12,
    gamesPlayed: 15,
    bestStreak: 7,
    accuracy: 88,
    badges: ['sakura_starter', 'word_warrior', 'japan_explorer'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'player-aoi',
    nickname: 'Aoi',
    avatar: 'cat',
    totalPoints: 5940,
    level: 11,
    gamesPlayed: 14,
    bestStreak: 8,
    accuracy: 87,
    badges: ['sakura_starter', 'hiragana_hero', 'mystery_solver'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
  },
  {
    id: 'player-kaito',
    nickname: 'Kaito',
    avatar: 'ninja',
    totalPoints: 5420,
    level: 10,
    gamesPlayed: 12,
    bestStreak: 7,
    accuracy: 85,
    badges: ['sakura_starter', 'kanji_master'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: 'player-hinata',
    nickname: 'Hinata',
    avatar: 'kitsune',
    totalPoints: 4980,
    level: 9,
    gamesPlayed: 11,
    bestStreak: 6,
    accuracy: 86,
    badges: ['sakura_starter', 'japan_explorer'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: 'player-sora',
    nickname: 'Sora',
    avatar: 'fuji',
    totalPoints: 4450,
    level: 8,
    gamesPlayed: 10,
    bestStreak: 5,
    accuracy: 84,
    badges: ['sakura_starter', 'hiragana_hero'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 16).toISOString(),
  },
  {
    id: 'player-mei',
    nickname: 'Mei',
    avatar: 'cat',
    totalPoints: 3890,
    level: 7,
    gamesPlayed: 9,
    bestStreak: 5,
    accuracy: 83,
    badges: ['sakura_starter'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: 'player-daiki',
    nickname: 'Daiki',
    avatar: 'samurai',
    totalPoints: 3410,
    level: 6,
    gamesPlayed: 8,
    bestStreak: 4,
    accuracy: 82,
    badges: ['sakura_starter'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
  {
    id: 'player-koharu',
    nickname: 'Koharu',
    avatar: 'sakura',
    totalPoints: 2950,
    level: 5,
    gamesPlayed: 7,
    bestStreak: 4,
    accuracy: 80,
    badges: ['sakura_starter'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 22).toISOString(),
  },
  {
    id: 'player-taro',
    nickname: 'Taro',
    avatar: 'tanuki',
    totalPoints: 2400,
    level: 4,
    gamesPlayed: 6,
    bestStreak: 3,
    accuracy: 78,
    badges: ['sakura_starter'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'player-yuta',
    nickname: 'Yuta',
    avatar: 'ninja',
    totalPoints: 1850,
    level: 3,
    gamesPlayed: 5,
    bestStreak: 3,
    accuracy: 75,
    badges: ['sakura_starter'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    lastPlayedAt: new Date(Date.now() - 3600000 * 26).toISOString(),
  },
];
